import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Providers} from "./providers";
import { ImageProvider } from './context/store';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TerraBloom',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        <ImageProvider>
        {children}
        </ImageProvider>
        </Providers>
        </body>
    </html>
  )
}
