import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Providers} from "./providers";
import { ImageProvider } from './context/store';
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TerraBloom',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <ClerkProvider>
    
    <html lang="en">
      <body className={inter.className}>
      <Providers>
      <ImageProvider>
        {children}
        <Toaster position='top-center' />
        </ImageProvider>
        </Providers>
        </body>
    </html>
   
        </ClerkProvider>
  )
}
